#ifndef __INPUT_H__
#define __INPUT_H__

#define KEY_W SDL_SCANCODE_W
#define KEY_A SDL_SCANCODE_A
#define KEY_S SDL_SCANCODE_S
#define KEY_D SDL_SCANCODE_D
#define KEY_Q SDL_SCANCODE_Q
#define KEY_E SDL_SCANCODE_E
#define KEY_SPACE SDL_SCANCODE_SPACE
#define KEY_LSHIFT SDL_SCANCODE_LSHIFT
#define KEY_RSHIFT SDL_SCANCODE_RSHIFT
#define KEY_LCTRL SDL_SCANCODE_LCTRL
#define KEY_RCTRL SDL_SCANCODE_RCTRL
#define KEY_UP SDL_SCANCODE_UP
#define KEY_DOWN SDL_SCANCODE_DOWN
#define KEY_LEFT SDL_SCANCODE_LEFT
#define KEY_RIGHT SDL_SCANCODE_RIGHT

#define KEY_PRESSED(KEY) keyboard_state_array[KEY]

#endif